[package]
name = "pom-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
pom-server.path = "../pom-server"

anyhow.workspace = true
clap.workspace = true
ratatui.workspace = true
thiserror.workspace = true
tokio.workspace = true
strum.workspace = true
