[package]
name = "pom-server"
version = "0.1.0"
edition = "2024"

[dependencies]
pom-config.path = "../pom-config/"
pom-shared.path = "../pom-shared/"

anyhow.workspace = true
libc.workspace = true
thiserror.workspace = true
tokio.workspace = true

