[package]
name = "cdi-server"
version = "0.1.0"
edition = "2024"

[dependencies]
cdi-config.path = "../cdi-config/"
cdi-shared.path = "../cdi-shared/"

anyhow.workspace = true
libc.workspace = true
thiserror.workspace = true
tokio.workspace = true

